export const projectsData = [
  {
    id: 1,
    title: 'Blog Away',
    intro: `An application where you can create an account, sign in if you are already a member. Create posts, update your own posts, delete your own posts. Everyone can view the posts, but only members can create a post and access other benefits.`,
    descripton: 'Lorem ipsum dolor',
    image: 'https://via.placeholder.com/200x200?text=placeholder',
    tech: [
      { key: 'MongoDB', value: 'MongoDB' },
      { key: 'REST', value: 'REST' },
      { key: 'Node', value: 'Node' },
      { key: 'React', value: 'React' },
      { key: 'Typescript', value: 'Typescript' },
      { key: 'S3', value: 'S3' },
    ],
    githubUrl: 'https://github.com/AndersenMattias/mern-blog-app',
    hostUrl: '',
  },
  {
    id: 2,
    title: 'Sudoku',
    intro: `This application was an good challenge, working with two dimensional arrays isn't an easy task. `,
    descripton: 'Lorem ipsum dolor',
    image: 'https://cdn-icons-png.flaticon.com/512/5190/5190808.png',
    tech: [
      { key: 'REST', value: 'REST' },
      { key: 'Node', value: 'Node' },
      { key: 'React', value: 'React' },
      { key: 'Javascript', value: 'Javascript' },
    ],
    githubUrl: 'https://github.com/AndersenMattias/sudoku-react-nodejs',
    hostUrl: 'https://sudoku-react-nodejs.herokuapp.com/',
  },
  {
    id: 3,
    title: 'Kosing',
    intro: `Having trouble telling your kids to do tasks at home? Well, this app might solve your problems. Parents can create accounts for their children, then assign different tasks that give different points. After certain points are reached, they can for example get that playstation they are always arguing about.`,
    descripton: 'Lorem ipsum dolor',
    image:
      'https://portfolio-mandersen-project-images.s3.eu-north-1.amazonaws.com/Kosing+startpage.png',
    tech: [
      { key: 'MongoDB', value: 'MongoDB' },
      { key: 'REST', value: 'REST' },
      { key: 'Node', value: 'Node' },
      { key: 'React', value: 'React' },
      { key: 'Typescript', value: 'Typescript' },
      { key: 'S3', value: 'S3' },
    ],
    githubUrl: 'https://github.com/AndersenMattias/Kosing',
    hostUrl: 'https://github.com/AndersenMattias/Kosing',
  },
  {
    id: 4,
    title: 'mattias-andersen.com',
    intro: `This portfolio website was built with React.js and Sass (scss) for styling.`,
    descripton: 'Lorem ipsum dolor',
    image: 'https://cdn-icons-png.flaticon.com/512/893/893505.png',
    tech: [
      { key: 'React', value: 'React' },
      { key: 'Javascript', value: 'Javascript' },
      { key: 'S3', value: 'S3' },
      { key: 'Sass', value: 'Sass' },
    ],
    githubUrl: 'https://github.com/AndersenMattias/mattias-andersen.com',
    hostUrl: 'https://mattias-andersen.com/',
  },
  {
    id: 5,
    title: 'First portfolio',
    intro: `My first portfolio website, created with simple HTML, CSS and vanilla Js.`,
    descripton: 'Lorem ipsum dolor',
    image: 'https://via.placeholder.com/200x200?text=placeholder',
    tech: [
      { key: 'HTML', value: 'HTML' },
      { key: 'CSS', value: 'CSS' },
      { key: 'Javascript', value: 'Javascript' },
    ],
    githubUrl: 'https://github.com/AndersenMattias/Matitas-website',
    hostUrl: '',
  },
];
